### ISSUE TITLE
Unable to see frames when LSP server is working

### ISSUE THREAD

**Issue by gbroques** [doums/lswip.nvim#1]
Hello, I'm trying to migrate from [lsp_spinner.nvim](https://github.com/doums/lsp_spinner.nvim) to `lswip.nvim`.

However, I don't see any spinner frames in my statusline when the LSP server is working.

Do you mind taking a quick look at the following commit to see if I'm missing something obvious?
https://github.com/gbroques/neovim-configuration/commit/95df3cddf6809cfdcb9244851ba6aeeda1494e85

I'm using [heirline.nvim](https://github.com/rebelot/heirline.nvim) to configure my statusline.

Also, this new plugin doesn't require notifying the LSP server of the `window/workDoneProgress` capability, or the `on_attach` handler?

Thank you for any help or insight you can provide! 

Apologies, I'm still new to Neovim and learning about things like autocmds and LSP servers.

**Comment by doums** [comment]
Hi, so I can see in your config `redrawstatus` is set to true, and you're calling `require('lswip').get`. If you are using only one main statusbar (`laststatus = 3`) it should just work.

If not, did you try with `redrawstatus = '!'` ?

I don't know `heirline.nvim` but it looks like your statusline is not redrawn/refreshed by `redrawstatus` calls.
Another way would be to make your statusline listen to `LswipUpdate` autocmd for update (if it's possible with heirline.nvim API).

**Comment by gbroques** [comment]
Thank you for the reply @doums!

By default [`laststatus`](https://neovim.io/doc/user/options.html#'laststatus') is `2`, so I set it to `3` to be sure.

Still didn't work.

I tried `redrawstatus = '!'` upon your suggestion, which didn't work either.

Lastly, I tried making my statusline listen to the `LswipUpdate` autocmd which is possible with heirline.nvim.

I defined an `LSPMessages` statusline component with the `update` property set to `"LswipUpdate"`.

From [heirline.nvim's docs](https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md?plain=1#L204-L206):
> **If `update` is** a function, the component will be updated whenever the function
> return value is `true`; else, **a `string`** or a `table` of strings **will be**
> **interpreted as autocommand event names that should trigger the component evaluation.**

```lua
local LSPMessages = {
  provider = require('lswip').get,
  -- .. omitted for brevity
  -- update this statusline component upon LswipUpdate autocmd
  update = "LswipUpdate"
}
```
However, I received the following error from [heirline.nvim/lua/heirliine/statusline.lua:256](https://github.com/rebelot/heirline.nvim/blob/master/lua/heirline/statusline.lua#L245-L256
):
```
E5108: Error executing lua ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:256: unexpected event
stack traceback:
	[C]: in function 'nvim_create_autocmd'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:256: in function 'register_update_autocmd'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:296: in function '_eval'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:440: in function 'eval'
	...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:109: in function <...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:104>
```

heirline.nvim says the `LswipUpdate` autocmd is unexpected when it passes `"LswipUpdate"` as the first argument to [`vim.api.nvim_create_autocmd`](https://neovim.io/doc/user/api.html#api-autocmd).

I'm calling `setup` for `lswip` **before** I call `setup` for `heirline.nvim`.

Do you have any thoughts, questions, or additional insights you can provide?

Any help is greatly appreciated!! :)

**Comment by doums** [comment]
Hey sorry for the delay, I'm using nvim compiled from `master` branch. I just updated `lswip` to run with nvim `0.10`, and there is no support for earlier versions.

**Comment by gbroques** [comment]
> Hey sorry for the delay, I'm using nvim compiled from `master` branch. I just updated `lswip` to run with nvim `0.10`, and there is no support for earlier versions.

No worries, thanks for the reply!

I'll consider trying this again when I upgrade to nvim `0.10` then.
